name: "Clientcide"

exports: "clientcide.js"

web: "[clientcide.com](http://clientcide.com)"

description: "Clientcide's plugins for MooTools"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [Aaron Newton](http://clientcide.com)"

authors: "[Aaron Newton](http://clientcide.com)"

version: "3.0.10"

sources: [
  Source/Core/dbug.js,
  Source/Behaviors/Behavior.Autocompleter.js,
  Source/Behaviors/Behavior.Tabs.js,
  Source/Layout/TabSwapper.js,
  Source/Layout/TabSwapper.Hash.js,
  Source/3rdParty/Autocompleter.js,
  Source/3rdParty/Autocompleter.JSONP.js,
  Source/3rdParty/Autocompleter.Local.js,
  Source/3rdParty/Autocompleter.Observer.js,
  Source/3rdParty/Autocompleter.Remote.js,
  Source/3rdParty/MooHashChange.js
]