name: "Clientcide"

exports: "clientcide.js"

web: "[clientcide.com](http://clientcide.com)"

description: "Clientcide's plugins for MooTools"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [Aaron Newton](http://clientcide.com)"

authors: "[Aaron Newton](http://clientcide.com)"

version: "3.0.5"

sources: [
  Source/Core/Clientcide.js,
  Source/Core/dbug.js,
  Source/Behaviors/Behavior.Autocompleter.js,
  Source/Behaviors/Behavior.Collapsible.js,
  Source/Behaviors/Behavior.Tabs.js,
  Source/Behaviors/Behavior.Tips.js,
  Source/Forms/Form.Validator.Tips.js,
  Source/Fx/Fx.Marquee.js,
  Source/Layout/Collapsible.js,
  Source/Layout/HoverGroup.js,
  Source/Layout/MooScroller.js,
  Source/Layout/MultipleOpenAccordion.js,
  Source/Layout/TabSwapper.js,
  Source/UI/StickyWin.js,
  Source/UI/StickyWin.Ajax.js,
  Source/UI/StickyWin.Alert.js,
  Source/UI/StickyWin.Confirm.js,
  Source/UI/StickyWin.Drag.js,
  Source/UI/StickyWin.Fx.js,
  Source/UI/StickyWin.Modal.js,
  Source/UI/StickyWin.PointyTip.js,
  Source/UI/StickyWin.Prompt.js,
  Source/UI/StickyWin.UI.js,
  Source/UI/StickyWin.UI.Pointy.js,
  Source/UI/StyleWriter.js,
  Source/UI/Tips.Pointy.js,
  Source/3rdParty/Autocompleter.js,
  Source/3rdParty/Autocompleter.Clientcide.js,
  Source/3rdParty/Autocompleter.JSONP.js,
  Source/3rdParty/Autocompleter.Local.js,
  Source/3rdParty/Autocompleter.Observer.js,
  Source/3rdParty/Autocompleter.Remote.js
]
version: 3.0.0
